apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: actor-mesh
spec:
  template:
    spec:
      containers:
      - name: gateway
        env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: RELOAD_ON_CHANGE
          value: "true"
        - name: ENABLE_DEBUG_ENDPOINTS
          value: "true"
        - name: CORS_ALLOW_ALL_ORIGINS
          value: "true"
        - name: RATE_LIMIT_DISABLED
          value: "true"
        - name: AUTH_DISABLED
          value: "true"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9000
          name: debug
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        volumeMounts:
        - name: dev-config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: dev-config
        configMap:
          name: dev-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: actor-mesh
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: debug
    port: 9000
    targetPort: 9000
    protocol: TCP
  type: LoadBalancer
