apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: actor-mesh-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - nats.yaml
  - redis.yaml
  - secrets.yaml
  - ingress.yaml
  - ../configmaps/app-config.yaml
  - ../deployments/gateway.yaml
  - ../deployments/actors.yaml
  - ../deployments/mock-services.yaml

commonLabels:
  app: actor-mesh-demo
  project: actor-mesh-demo
  managed-by: kustomize

commonAnnotations:
  version: v1.0.0
  description: "E-commerce Support Agent Actor Mesh Demo"
  contact: "demo@actormesh.com"
  documentation: "https://github.com/actormesh/actor-mesh-demo"

images:
  - name: actor-mesh/actor-mesh-demo
    newTag: latest

configMapGenerator:
  - name: app-version
    namespace: actor-mesh
    literals:
      - VERSION=1.0.0
      - BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      - GIT_COMMIT=unknown

secretGenerator:
  - name: app-runtime-secrets
    namespace: actor-mesh
    type: Opaque
    literals:
      - RUNTIME_SECRET=$(openssl rand -base64 32)
    options:
      disableNameSuffixHash: true

patches:
  # Add common environment variables to all deployments
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KUSTOMIZE_BUILD_TIME
          valueFrom:
            configMapKeyRef:
              name: app-version
              key: BUILD_TIME
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KUSTOMIZE_VERSION
          valueFrom:
            configMapKeyRef:
              name: app-version
              key: VERSION

replicas:
  - name: gateway
    count: 2
  - name: sentiment-analyzer
    count: 1
  - name: intent-analyzer
    count: 1
  - name: context-retriever
    count: 1
  - name: response-generator
    count: 1
  - name: guardrail-validator
    count: 1
  - name: execution-coordinator
    count: 1
  - name: decision-router
    count: 1
  - name: escalation-router
    count: 1
  - name: response-aggregator
    count: 1
  - name: mock-services
    count: 1

# Namespace for all resources
namespace: actor-mesh

# Name prefix for generated resources
namePrefix: ""

# Name suffix for generated resources
nameSuffix: ""

# Common annotations to add to all resources
buildMetadata:
  - originAnnotations
  - transformerAnnotations
