apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: actor-mesh
  labels:
    app: redis
    component: cache
    version: v7.0.0
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: actor-mesh
  labels:
    app: redis
    component: cache
    version: v7.0.0
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: cache
        version: v7.0.0
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - "redis-server"
        - "/etc/redis/redis.conf"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
              optional: true
        volumeMounts:
        - name: config-volume
          mountPath: /etc/redis
        - name: redis-storage
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config-volume
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: actor-mesh
  labels:
    app: redis
    component: config
data:
  redis.conf: |
    # Redis Configuration for Actor Mesh Demo

    # Basic Configuration
    bind 0.0.0.0
    port 6379

    # Persistence Configuration
    appendonly yes
    appendfsync everysec

    # Memory Management
    maxmemory 256mb
    maxmemory-policy allkeys-lru

    # Logging
    loglevel notice

    # Security (password will be set via environment variable if provided)
    protected-mode no

    # Performance
    tcp-keepalive 300
    timeout 0

    # Snapshotting
    save 900 1
    save 300 10
    save 60 10000

    # Client Configuration
    tcp-backlog 511

    # Slow Log
    slowlog-log-slower-than 10000
    slowlog-max-len 128

    # Database Configuration
    databases 16
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: actor-mesh
  labels:
    app: redis
    component: secret
type: Opaque
data:
  # Default password (base64 encoded "redis123")
  # Change this in production!
  password: cmVkaXMxMjM=
